### ISSUE TITLE
Missed Tip in 1ml rack

### ISSUE THREAD

**Issue by RayC17** [theosanderson/PlasmoTron#10]
A new 1ml rack was used for splitting to a new plate. When I came back the 24th(ish) tip had been skipped.
Not sure what caused the problem, found split volume and transferred by hand.

**Comment by theosanderson** [comment]
We will now home and discard (any) tips on the pipettes before each run. Hopefully this will resolve this and @RussHobbs issue. https://github.com/theosanderson/PlasmoTron/commit/64302e36c6297ce36c277d97aa34bdb3adfbae5d
