### ISSUE TITLE
receiving notification when job is over

### ISSUE THREAD

**Issue by RussHobbs** [theosanderson/PlasmoTron#12]
Could be interesting to set up a notification system (email?) to receive a short text when the job is over. It could be very usefull when running many plates instead of waiting and checking regularly

**Comment by theosanderson** [comment]
This makes a lot of sense - I think we probably need a database table of users (which would be useful anyway) to make it happen

**Comment by theosanderson** [comment]
Should be sorted for job finishing and tip refill prompts!
