### ISSUE TITLE
Calculate time estimate

### ISSUE THREAD

**Issue by theosanderson** [theosanderson/PlasmoTron#8]

**Comment by RussHobbs** [comment]
1h/24WP. 1ml/well. feed and keep 80%.

**Comment by theosanderson** [comment]
Wow - that is slow. Can probably make the resuspension less rigorous for this. It is currently set up imagining that one wants to split a lot so resuspension is important to ensure that enough is discarded - less important the other way round.

**Comment by RussHobbs** [comment]
It is probably around 50min only pipetting but counted some extra time for changing loading blabla

**Comment by RussHobbs** [comment]
Feeding protocol, 24WP, 1ml per plate takes 15min/plate

**Comment by theosanderson** [comment]
Thanks, if interested here is how long each command tends to take:

https://imgur.com/a/pwc7z
